---
- name: Patch RHEL and Oracle Linux systems
  hosts: all
  become: true
  gather_facts: true

  vars:
    reboot_after_patch: true
    exclude_packages: []

  pre_tasks:
    - name: Verify OS is RHEL or Oracle Linux
      ansible.builtin.assert:
        that:
          - ansible_distribution in ["RedHat", "OracleLinux"]
        fail_msg: "This playbook supports only RHEL or Oracle Linux systems."
        success_msg: "OS verification passed."

    - name: Print OS and version
      ansible.builtin.debug:
        msg: "Running on {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

  tasks:
    - name: Clean yum metadata
      ansible.builtin.command: yum clean all
      register: clean_result
      changed_when: "'Deleted' in clean_result.stdout"

    - name: Update all packages (excluding if defined)
      ansible.builtin.yum:
        name: "*"
        state: latest
        exclude: "{{ exclude_packages | join(',') if exclude_packages else omit }}"
      register: update_result

    - name: Print summary of updated packages
      ansible.builtin.debug:
        var: update_result

  post_tasks:
    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_flag
      changed_when: false

    - name: Reboot the system if needed
      ansible.builtin.reboot:
        msg: "Rebooting after patching..."
        reboot_timeout: 600
      when: reboot_after_patch and reboot_flag.stat.exists

    - name: Confirm system is back online
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Display completion message
      ansible.builtin.debug:
        msg: "Patching completed successfully on {{ inventory_hostname }}"
